<a href="https://colab.research.google.com/github/Basit-sta/ADVANCED-PROGRAMMING-FOR-AI-PRACTICAL-ASSIGNMENT/blob/main/assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# ============================================
# ADVANCED PROGRAMMING FOR AI - ASSIGNMENT
# Building an AI-Ready Dataset Using Web Scraping, External Datasets, NumPy, and Pandas
# ============================================

# Student Name: [Abdul Basit Stanikzai]
# Student ID: [01]
# Semester: Spring 2026

In [ ]:
# ============================================
# PART A: Web Scraping from Books to Scrape (FIXED)
# ============================================
# 01 Import all required libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import re
import time
from urllib.parse import urljoin
import warnings
warnings.filterwarnings('ignore')

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

print("All libraries imported successfully!")
print(f"Pandas version: {pd.__version__}")
print(f"NumPy version: {np.__version__}")

All libraries imported successfully!
Pandas version: 2.2.2
NumPy version: 2.0.2

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re
from urllib.parse import urljoin

# ============================================
# PART A: WEB SCRAPING AND DATA COLLECTION
# ============================================

def scrape_books(base_url="https://books.toscrape.com/"):

    all_books = []

    rating_map = {
        "One": 1,
        "Two": 2,
        "Three": 3,
        "Four": 4,
        "Five": 5
    }

    headers = {
        "User-Agent": "Mozilla/5.0"
    }

    # Reuse HTTP connection (faster)
    session = requests.Session()

    print("=" * 60)
    print("Starting Web Scraping...")
    print("=" * 60)

    for page in range(1, 51):

        url = f"{base_url}catalogue/page-{page}.html"

        try:

            response = session.get(url, headers=headers, timeout=10)

            if response.status_code != 200:
                print(f"Page {page} not found.")
                break

            soup = BeautifulSoup(response.text, "html.parser")

            books = soup.find_all("article", class_="product_pod")

            if not books:
                break

            for book in books:

                # Title
                title = book.h3.a["title"]

                # Price
                price_text = book.find("p", class_="price_color").text
                price = float(re.sub(r"[^\d.]", "", price_text))

                # Rating
                rating_text = book.find("p", class_="star-rating")["class"][1]
                rating_numeric = rating_map.get(rating_text, 0)

                # Availability
                availability = book.find(
                    "p",
                    class_="instock availability"
                ).get_text(strip=True)

                # Product Link
                relative_link = book.h3.a["href"]
                product_link = urljoin(
                    base_url + "catalogue/",
                    relative_link
                )

                all_books.append({
                    "title": title,
                    "price_gbp": price,
                    "rating_numeric": rating_numeric,
                    "availability": availability,
                    "product_link": product_link,
                    "page": page
                })

            print(f"✓ Page {page} completed ({len(all_books)} books)")

        except Exception as e:
            print(f"Error on page {page}: {e}")
            break

    print("\nScraping completed successfully!")
    print(f"Total Books Scraped: {len(all_books)}")

    return pd.DataFrame(all_books)


# ============================================
# Execute Scraping
# ============================================

df_scraped = scrape_books()

# ============================================
# Display Dataset
# ============================================

print("\nFirst 5 Records")
display(df_scraped.head())

print("\nDataset Shape")
print(df_scraped.shape)

print("\nDataset Information")
print(df_scraped.info())

print("\nSummary Statistics")
display(df_scraped.describe())

# ============================================
# Save Raw Dataset
# ============================================

df_scraped.to_csv(
    "scraped_raw_dataset.csv",
    index=False,
    encoding="utf-8"
)

print("\n✓ Dataset saved as 'scraped_raw_dataset.csv'")

# ============================================
# Basic Analysis
# ============================================

print("\nTotal Books :", len(df_scraped))
print("Unique Books :", df_scraped["title"].nunique())
print("Average Price : £", round(df_scraped["price_gbp"].mean(), 2))
print("Maximum Price : £", df_scraped["price_gbp"].max())
print("Minimum Price : £", df_scraped["price_gbp"].min())

print("\nRating Distribution")
print(df_scraped["rating_numeric"].value_counts().sort_index())

print("\nAvailability")
print(df_scraped["availability"].value_counts())

============================================================
Starting Web Scraping...
============================================================
✓ Page 1 completed (20 books)
✓ Page 2 completed (40 books)
✓ Page 3 completed (60 books)
✓ Page 4 completed (80 books)
✓ Page 5 completed (100 books)
✓ Page 6 completed (120 books)
✓ Page 7 completed (140 books)
✓ Page 8 completed (160 books)
✓ Page 9 completed (180 books)
✓ Page 10 completed (200 books)
✓ Page 11 completed (220 books)
✓ Page 12 completed (240 books)
✓ Page 13 completed (260 books)
✓ Page 14 completed (280 books)
✓ Page 15 completed (300 books)
✓ Page 16 completed (320 books)
✓ Page 17 completed (340 books)
✓ Page 18 completed (360 books)
✓ Page 19 completed (380 books)
✓ Page 20 completed (400 books)
✓ Page 21 completed (420 books)
✓ Page 22 completed (440 books)
✓ Page 23 completed (460 books)
✓ Page 24 completed (480 books)
✓ Page 25 completed (500 books)
✓ Page 26 completed (520 books)
✓ Page 27 completed (540 books)
✓ Page 28 completed (560 books)
✓ Page 29 completed (580 books)
✓ Page 30 completed (600 books)
✓ Page 31 completed (620 books)
✓ Page 32 completed (640 books)
✓ Page 33 completed (660 books)
✓ Page 34 completed (680 books)
✓ Page 35 completed (700 books)
✓ Page 36 completed (720 books)
✓ Page 37 completed (740 books)
✓ Page 38 completed (760 books)
✓ Page 39 completed (780 books)
✓ Page 40 completed (800 books)
✓ Page 41 completed (820 books)
✓ Page 42 completed (840 books)
✓ Page 43 completed (860 books)
✓ Page 44 completed (880 books)
✓ Page 45 completed (900 books)
✓ Page 46 completed (920 books)
✓ Page 47 completed (940 books)
✓ Page 48 completed (960 books)
✓ Page 49 completed (980 books)
✓ Page 50 completed (1000 books)

Scraping completed successfully!
Total Books Scraped: 1000

First 5 Records

,title,price_gbp,rating_numeric,availability,product_link,page
0,A Light in the Attic,51.77,3,In stock,https://books.toscrape.com/catalogue/a-light-i...,1
1,Tipping the Velvet,53.74,1,In stock,https://books.toscrape.com/catalogue/tipping-t...,1
2,Soumission,50.10,1,In stock,https://books.toscrape.com/catalogue/soumissio...,1
3,Sharp Objects,47.82,4,In stock,https://books.toscrape.com/catalogue/sharp-obj...,1
4,Sapiens: A Brief History of Humankind,54.23,5,In stock,https://books.toscrape.com/catalogue/sapiens-a...,1

Dataset Shape
(1000, 6)

Dataset Information
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           1000 non-null   object
 1   price_gbp       1000 non-null   float64
 2   rating_numeric  1000 non-null   int64
 3   availability    1000 non-null   object
 4   product_link    1000 non-null   object
 5   page            1000 non-null   int64
dtypes: float64(1), int64(2), object(3)
memory usage: 47.0+ KB
None

Summary Statistics

        price_gbp  rating_numeric         page
count  1000.00000     1000.000000  1000.000000
mean     35.07035        2.923000    25.500000
std      14.44669        1.434967    14.438091
min      10.00000        1.000000     1.000000
25%      22.10750        2.000000    13.000000
50%      35.98000        3.000000    25.500000
75%      47.45750        4.000000    38.000000
max      59.99000        5.000000    50.000000

✓ Dataset saved as 'scraped_raw_dataset.csv'

Total Books : 1000
Unique Books : 999
Average Price : £ 35.07
Maximum Price : £ 59.99
Minimum Price : £ 10.0

Rating Distribution
rating_numeric
1    226
2    196
3    203
4    179
5    196
Name: count, dtype: int64

Availability
availability
In stock    1000
Name: count, dtype: int64

In [96]:
#Part B: Loading an External Dataset


# For CSV

#  https://www.kaggle.com/datasets/rudrakumargupta/comic-books-dataset-10000-entries?resource=download
df_external = pd.read_csv("external_dataset.csv")
#df = pd.read_csv("external_dataset.csv")

# Inspect the external dataset
df_external.head()
df_external.shape
df_external.info()
df_external.describe()
df_external.isna().sum()
df_external.to_csv("external_raw_dataset.csv", index=False, encoding="utf-8")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 998 entries, 0 to 997
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   availability    998 non-null    int64
 1   category        998 non-null    object
 2   description     998 non-null    object
 3   num_reviews     998 non-null    int64
 4   price           998 non-null    float64
 5   price_excl_tax  998 non-null    float64
 6   price_incl_tax  998 non-null    float64
 7   product_type    998 non-null    object
 8   stars           998 non-null    int64
 9   tax             998 non-null    float64
 10  title           998 non-null    object
 11  upc             998 non-null    object
 12  url             998 non-null    object
dtypes: float64(4), int64(3), object(6)
memory usage: 101.5+ KB

In [ ]:
#1. Inspect Both Datasets

#For the scraped dataset:

# Inspect scraped dataset
df_scraped.head()
df_scraped.tail()
df_scraped.shape
df_scraped.info()
df_scraped.describe()
df_scraped.columns
df_scraped.dtypes
df_scraped.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           1000 non-null   object
 1   price_gbp       1000 non-null   float64
 2   rating_numeric  1000 non-null   int64
 3   availability    1000 non-null   object
 4   product_link    1000 non-null   object
 5   page            1000 non-null   int64
dtypes: float64(1), int64(2), object(3)
memory usage: 47.0+ KB

title             0
price_gbp         0
rating_numeric    0
availability      0
product_link      0
page              0
dtype: int64

In [ ]:
# For the external dataset:

# Inspect external dataset
df_external.head()
df_external.tail()
df_external.shape
df_external.info()
df_external.describe()
df_external.columns
df_external.dtypes
df_external.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 998 entries, 0 to 997
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   availability    998 non-null    int64
 1   category        998 non-null    object
 2   description     998 non-null    object
 3   num_reviews     998 non-null    int64
 4   price           998 non-null    float64
 5   price_excl_tax  998 non-null    float64
 6   price_incl_tax  998 non-null    float64
 7   product_type    998 non-null    object
 8   stars           998 non-null    int64
 9   tax             998 non-null    float64
 10  title           998 non-null    object
 11  upc             998 non-null    object
 12  url             998 non-null    object
dtypes: float64(4), int64(3), object(6)
memory usage: 101.5+ KB

availability      0
category          0
description       0
num_reviews       0
price             0
price_excl_tax    0
price_incl_tax    0
product_type      0
stars             0
tax               0
title             0
upc               0
url               0
dtype: int64

In [ ]:
#df_scraped.isna().sum()
df_external.isna().sum()

availability      0
category          0
description       0
num_reviews       0
price             0
price_excl_tax    0
price_incl_tax    0
product_type      0
stars             0
tax               0
title             0
upc               0
url               0
dtype: int64

In [ ]:
df_scraped=df_scraped.dropna()
df_external=df_external.dropna()

In [ ]:
#3. Remove Duplicate Records
df_scraped.duplicated().sum()
df_scraped = df_scraped.drop_duplicates()      # there is no duplicate value so no need to run this code

In [ ]:
#4. Clean Text Columns

#df_scraped["title"] = df_scraped["title"].str.strip()
#df_scraped["price_gbp"] = df_scraped["price_gbp"].str.strip()
#df_scraped["rating_numeric"] = df_scraped["rating_numeric"].str.replace('"', '')

In [ ]:
#5. Convert Data Types                      there is no need for converting

# Example for price
#df["price"] = df["price"].str.replace("GBP", "").astype(float)
# Example for rating
#rating_map = {
# "One": 1,
# "Two": 2,
# "Three": 3,
# "Four": 4,
# "Five": 5
#}
#df["rating_numeric"] = df["rating"].map(rating_map)

In [ ]:
df_scraped.head()

,title,price_gbp,rating_numeric,availability,product_link,page
0,A Light in the Attic,51.77,3,In stock,https://books.toscrape.com/catalogue/a-light-i...,1
1,Tipping the Velvet,53.74,1,In stock,https://books.toscrape.com/catalogue/tipping-t...,1
2,Soumission,50.10,1,In stock,https://books.toscrape.com/catalogue/soumissio...,1
3,Sharp Objects,47.82,4,In stock,https://books.toscrape.com/catalogue/sharp-obj...,1
4,Sapiens: A Brief History of Humankind,54.23,5,In stock,https://books.toscrape.com/catalogue/sapiens-a...,1

In [ ]:
#6. Filtering
# 1. Books with rating 4 or 5
df_high_rating = df_scraped[df_scraped["rating_numeric"] >= 4]

# 2. Books currently in stock
df_available = df_scraped[df_scraped["availability"] == "In stock"]

# 3. Books costing more than £40
df_expensive = df_scraped[df_scraped["price_gbp"] > 40]

print("High Rating Books:", len(df_high_rating))
print("Available Books:", len(df_available))
print("Expensive Books:", len(df_expensive))
df_scraped.head()

High Rating Books: 375
Available Books: 1000
Expensive Books: 403

,title,price_gbp,rating_numeric,availability,product_link,page
0,A Light in the Attic,51.77,3,In stock,https://books.toscrape.com/catalogue/a-light-i...,1
1,Tipping the Velvet,53.74,1,In stock,https://books.toscrape.com/catalogue/tipping-t...,1
2,Soumission,50.10,1,In stock,https://books.toscrape.com/catalogue/soumissio...,1
3,Sharp Objects,47.82,4,In stock,https://books.toscrape.com/catalogue/sharp-obj...,1
4,Sapiens: A Brief History of Humankind,54.23,5,In stock,https://books.toscrape.com/catalogue/sapiens-a...,1

In [ ]:
#6-2. Filtering
# 1. Books with rating 4 or 5
df_high_rating = df_external[df_external["stars"] >= 4]

# 2. Books currently in stock
df_category = df_external[df_external["category"] == "science"]

# 3. Books costing more than £40
df_expensive = df_external[df_external["price"] > 40]

print("High Rating Books:", len(df_high_rating))
print("category Books:", len(df_available))
print("Expensive Books:", len(df_expensive))
df_external.head()

High Rating Books: 375
category Books: 1000
Expensive Books: 402

,availability,category,description,num_reviews,price,price_excl_tax,price_incl_tax,product_type,stars,tax,title,upc,url
0,19,default,"Since her assault, Miss Annette Chetwynd has b...",0,13.99,13.99,13.99,books,2,0.0,"Since her assault, Miss Annette Chetwynd has b...",0312262ecafa5a40,https://books.toscrape.com/catalogue/starving-...
1,20,fiction,"Dans une France assez proche de la nôtre, un h...",0,50.10,50.10,50.10,books,1,0.0,"Dans une France assez proche de la nôtre, un h...",6957f44c3847a760,https://books.toscrape.com/catalogue/soumissio...
2,19,young adult,Patient Twenty-nine.A monster roams the halls ...,0,22.65,22.65,22.65,books,1,0.0,Patient Twenty-nine.A monster roams the halls ...,f77dbf2323deb740,https://books.toscrape.com/catalogue/the-requi...
3,20,history,From a renowned historian comes a groundbreaki...,0,54.23,54.23,54.23,books,5,0.0,From a renowned historian comes a groundbreaki...,4165285e1663650f,https://books.toscrape.com/catalogue/sapiens-a...
4,20,historical fiction,"""Erotic and absorbing...Written with starling ...",0,53.74,53.74,53.74,books,1,0.0,"""Erotic and absorbing...Written with starling ...",90fa61229261140a,https://books.toscrape.com/catalogue/tipping-t...

In [ ]:
#7. Sorting
#Students must sort the data based on at least 2 meaningful columns.
df_scraped.sort_values("price_gbp", ascending=False)
#df_scraped.sort_values(["rating_numeric", "rating_numeric"], ascending=[False,True])

,title,price_gbp,rating_numeric,availability,product_link,page
648,The Perfect Play (Play by Play #1),59.99,3,In stock,https://books.toscrape.com/catalogue/the-perfe...,33
617,Last One Home (New Beginnings #1),59.98,3,In stock,https://books.toscrape.com/catalogue/last-one-...,31
860,Civilization and Its Discontents,59.95,2,In stock,https://books.toscrape.com/catalogue/civilizat...,44
560,The Barefoot Contessa Cookbook,59.92,5,In stock,https://books.toscrape.com/catalogue/the-baref...,29
366,The Diary of a Young Girl,59.90,3,In stock,https://books.toscrape.com/catalogue/the-diary...,19
...,...,...,...,...,...,...
302,Greek Mythic History,10.23,5,In stock,https://books.toscrape.com/catalogue/greek-myt...,16
84,Patience,10.16,3,In stock,https://books.toscrape.com/catalogue/patience_...,5
716,The Tipping Point: How Little Things Can Make ...,10.02,2,In stock,https://books.toscrape.com/catalogue/the-tippi...,36
501,The Origin of Species,10.01,4,In stock,https://books.toscrape.com/catalogue/the-origi...,26
638,An Abundance of Katherines,10.00,5,In stock,https://books.toscrape.com/catalogue/an-abunda...,32

In [ ]:
#7-2. Sorting
#Students must sort the data based on at least 2 meaningful columns.
df_external.sort_values("price", ascending=False)

,availability,category,description,num_reviews,price,price_excl_tax,price_incl_tax,product_type,stars,tax,title,upc,url
650,4,romance,"Football pro Mick Riley is an all-star, both o...",0,59.99,59.99,59.99,books,3,0.0,"Football pro Mick Riley is an all-star, both o...",9cc207168a03470d,https://books.toscrape.com/catalogue/the-perfe...
606,5,fiction,"Growing up, Cassie Carter and her sisters, Kar...",0,59.98,59.98,59.98,books,3,0.0,"Growing up, Cassie Carter and her sisters, Kar...",07e6810fd3236bda,https://books.toscrape.com/catalogue/last-one-...
876,3,psychology,It stands as a brilliant summary of the views ...,0,59.95,59.95,59.95,books,2,0.0,It stands as a brilliant summary of the views ...,396385e3de5d18c3,https://books.toscrape.com/catalogue/civilizat...
577,6,food and drink,"For more than twenty years, Barefoot Contessa,...",0,59.92,59.92,59.92,books,5,0.0,"For more than twenty years, Barefoot Contessa,...",6478ccb4416e6a5d,https://books.toscrape.com/catalogue/the-baref...
373,12,nonfiction,Discovered in the attic in which she spent the...,0,59.90,59.90,59.90,books,3,0.0,Discovered in the attic in which she spent the...,54fc03f1e1d355db,https://books.toscrape.com/catalogue/the-diary...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
316,14,default,As far back as the fifth century BCE Pherecyde...,0,10.23,10.23,10.23,books,5,0.0,As far back as the fifth century BCE Pherecyde...,f201f263d8c23f97,https://books.toscrape.com/catalogue/greek-myt...
94,16,sequential art,Patience is a psychedelic science-fiction love...,0,10.16,10.16,10.16,books,3,0.0,Patience is a psychedelic science-fiction love...,9429b4d59c537af5,https://books.toscrape.com/catalogue/patience_...
702,3,add a comment,The tipping point is that magic moment when an...,0,10.02,10.02,10.02,books,2,0.0,The tipping point is that magic moment when an...,224fa77d4b248046,https://books.toscrape.com/catalogue/the-tippi...
504,7,science,The publication of Darwin’s The Origin of Spec...,0,10.01,10.01,10.01,books,4,0.0,The publication of Darwin’s The Origin of Spec...,0345872b14f9e774,https://books.toscrape.com/catalogue/the-origi...
625,5,young adult,Katherine V thought boys were gross Katherine ...,0,10.00,10.00,10.00,books,5,0.0,Katherine V thought boys were gross Katherine ...,f36d24c309e87e5b,https://books.toscrape.com/catalogue/an-abunda...

In [ ]:
# 8. Grouping and Aggregation

# Average price by rating
print(df_scraped.groupby("rating_numeric")["price_gbp"].mean())

# Number of books by rating
print(df_scraped.groupby("rating_numeric")["title"].count())

# Price statistics by availability
print(df_scraped.groupby("availability")["price_gbp"].agg(
    ["mean", "min", "max"]
))

# Average price by page
print(df_scraped.groupby("page")["price_gbp"].mean())

rating_numeric
1    34.561195
2    34.810918
3    34.692020
4    36.093296
5    35.374490
Name: price_gbp, dtype: float64
rating_numeric
1    226
2    196
3    203
4    179
5    196
Name: title, dtype: int64
                  mean   min    max
availability
In stock      35.07035  10.0  59.99
page
1     38.0485
2     31.8690
3     35.0905
4     37.8255
5     29.9700
6     36.2855
7     38.3415
8     36.4565
9     29.6000
10    34.4755
11    30.0075
12    37.4725
13    30.4765
14    35.4375
15    32.5875
16    37.1355
17    39.0340
18    32.4805
19    38.2755
20    38.3265
21    29.7475
22    36.7740
23    40.0910
24    34.6265
25    35.5750
26    33.9210
27    34.8610
28    36.2040
29    40.0385
30    37.5545
31    26.6650
32    34.2985
33    35.5520
34    29.4575
35    34.4540
36    34.6705
37    36.4655
38    37.7350
39    35.8820
40    32.9860
41    37.3460
42    37.8460
43    35.6810
44    32.6315
45    32.2145
46    36.2735
47    31.4840
48    34.8115
49    41.2750
50    37.1995
Name: price_gbp, dtype: float64

In [ ]:
# 8-2 Grouping Operation for external Dataset
group1 = df_external.groupby("category")["price"].mean()
print(group1)

# Grouping Operation 2
group2 = df_external.groupby("category")["title"].count()
print(group2)

# Grouping Operation 3
group3 = df_external.groupby("stars")["price"].agg(["mean", "min", "max"])
print(group3)

category
academic              13.120000
add a comment         35.796418
adult fiction         15.360000
art                   38.520000
autobiography         37.053333
biography             33.662000
business              32.460000
childrens             32.638276
christian             42.496667
christian fiction     34.385000
classics              35.490556
contemporary          36.200000
crime                 10.970000
cultural              36.580000
default               34.408543
erotica               19.190000
fantasy               39.593958
fiction               36.066615
food and drink        31.414667
health                51.452500
historical            22.830000
historical fiction    33.644231
history               37.295000
horror                35.949412
humor                 33.501000
music                 35.636923
mystery               31.719062
new adult             46.383333
nonfiction            34.260182
novels                54.810000
paranormal            15.400000
parenting             37.350000
philosophy            33.558182
poetry                35.974211
politics              53.613333
psychology            34.218571
religion              32.567143
romance               33.933714
science               33.088571
science fiction       33.802500
self help             40.620000
sequential art        34.572267
short stories         35.880000
spirituality          35.098333
sports and games      41.166000
suspense              58.330000
thriller              31.433636
travel                39.794545
womens fiction        36.791176
young adult           35.449074
Name: price, dtype: float64
category
academic                1
add a comment          67
adult fiction           1
art                     8
autobiography           9
biography               5
business               12
childrens              29
christian               3
christian fiction       6
classics               18
contemporary            3
crime                   1
cultural                1
default               151
erotica                 1
fantasy                48
fiction                65
food and drink         30
health                  4
historical              2
historical fiction     26
history                18
horror                 17
humor                  10
music                  13
mystery                32
new adult               6
nonfiction            110
novels                  1
paranormal              1
parenting               1
philosophy             11
poetry                 19
politics                3
psychology              7
religion                7
romance                35
science                14
science fiction        16
self help               5
sequential art         75
short stories           1
spirituality            6
sports and games        5
suspense                1
thriller               11
travel                 11
womens fiction         17
young adult            54
Name: title, dtype: int64
            mean    min    max
stars
1      34.468000  10.40  59.64
2      34.810918  10.02  59.95
3      34.705347  10.16  59.99
4      36.093296  10.01  59.45
5      35.374490  10.00  59.92

In [ ]:
#9. Feature Engineering for Web Scrapp data set
#Students must create at least 4 new features.
# Examples for books
# 1. Title length
df_scraped["title_length"] = df_scraped["title"].str.len()

# 2. Is the book expensive?
df_scraped["is_expensive"] = df_scraped["price_gbp"] > df_scraped["price_gbp"].mean()

# 3. Price level
df_scraped["price_level"] = pd.cut(
    df_scraped["price_gbp"],
    bins=[0, 20, 40, 100],
    labels=["Low", "Medium", "High"]
)

# 4. Rating level
df_scraped["rating_level"] = df_scraped["rating_numeric"].apply(
    lambda x: "High" if x >= 4 else "Low"
)

# View the new features
df_scraped.head()

,title,price_gbp,rating_numeric,availability,product_link,page,title_length,is_expensive,price_level,rating_level
0,A Light in the Attic,51.77,3,In stock,https://books.toscrape.com/catalogue/a-light-i...,1,20,True,High,Low
1,Tipping the Velvet,53.74,1,In stock,https://books.toscrape.com/catalogue/tipping-t...,1,18,True,High,Low
2,Soumission,50.10,1,In stock,https://books.toscrape.com/catalogue/soumissio...,1,10,True,High,Low
3,Sharp Objects,47.82,4,In stock,https://books.toscrape.com/catalogue/sharp-obj...,1,13,True,High,High
4,Sapiens: A Brief History of Humankind,54.23,5,In stock,https://books.toscrape.com/catalogue/sapiens-a...,1,37,True,High,High

In [ ]:


#9-2. Feature Engineering for External Dataset
#Students must create at least 4 new features.
# Examples for books

# 1. Length of book title
df_external["title_length"] = df_external["title"].str.len()

# 2. Is the book expensive?
df_external["is_expensive"] = (
    df_external["price"] > df_external["price"].mean()
)

# 3. Price category
df_external["price_level"] = pd.cut(
    df_external["price"],
    bins=[0, 20, 40, 60],
    labels=["Low", "Medium", "High"]
)

# 4. Review popularity
df_external["review_popularity"] = pd.cut(
    df_external["num_reviews"],
    bins=[-1, 10, 30, 1000],
    labels=["Low", "Medium", "High"]
)

# Display new features
df_external.head()

,availability,category,description,num_reviews,price,price_excl_tax,price_incl_tax,product_type,stars,tax,title,upc,url,title_length,is_expensive,price_level,review_popularity
0,19,default,"Since her assault, Miss Annette Chetwynd has b...",0,13.99,13.99,13.99,books,2,0.0,"Since her assault, Miss Annette Chetwynd has b...",0312262ecafa5a40,https://books.toscrape.com/catalogue/starving-...,1204,False,Low,Low
1,20,fiction,"Dans une France assez proche de la nôtre, un h...",0,50.10,50.10,50.10,books,1,0.0,"Dans une France assez proche de la nôtre, un h...",6957f44c3847a760,https://books.toscrape.com/catalogue/soumissio...,1093,True,High,Low
2,19,young adult,Patient Twenty-nine.A monster roams the halls ...,0,22.65,22.65,22.65,books,1,0.0,Patient Twenty-nine.A monster roams the halls ...,f77dbf2323deb740,https://books.toscrape.com/catalogue/the-requi...,995,False,Medium,Low
3,20,history,From a renowned historian comes a groundbreaki...,0,54.23,54.23,54.23,books,5,0.0,From a renowned historian comes a groundbreaki...,4165285e1663650f,https://books.toscrape.com/catalogue/sapiens-a...,1945,True,High,Low
4,20,historical fiction,"""Erotic and absorbing...Written with starling ...",0,53.74,53.74,53.74,books,1,0.0,"""Erotic and absorbing...Written with starling ...",90fa61229261140a,https://books.toscrape.com/catalogue/tipping-t...,1029,True,High,Low

In [ ]:
#Step 1: Check how many titles match

#Before merging:
common_titles = set(df_scraped["title"]).intersection(set(df_external["title"]))

print("Number of matching titles:", len(common_titles))

Number of matching titles: 1

In [ ]:
# Merge datasets using common column "title"

merged_df = pd.merge(
    df_scraped,
    df_external,
    on="title",
    how="inner"
)

print("Rows in scraped dataset:", len(df_scraped))
print("Rows in external dataset:", len(df_external))
print("Rows after merging:", len(merged_df))

print("\nMissing Values:")
print(merged_df.isna().sum())

merged_df.head()

Rows in scraped dataset: 1000
Rows in external dataset: 998
Rows after merging: 1

Missing Values:
title                0
price_gbp            0
rating_numeric       0
availability_x       0
product_link         0
page                 0
title_length_x       0
is_expensive_x       0
price_level_x        0
rating_level         0
availability_y       0
category             0
description          0
num_reviews          0
price                0
price_excl_tax       0
price_incl_tax       0
product_type         0
stars                0
tax                  0
upc                  0
url                  0
title_length_y       0
is_expensive_y       0
price_level_y        0
review_popularity    0
dtype: int64

,title,price_gbp,rating_numeric,availability_x,product_link,page,title_length_x,is_expensive_x,price_level_x,rating_level,...,price_incl_tax,product_type,stars,tax,upc,url,title_length_y,is_expensive_y,price_level_y,review_popularity
0,Kindle Paperwhite User's Guide,34.0,3,In stock,https://books.toscrape.com/catalogue/kindle-pa...,45,30,False,Medium,Low,...,34.0,books,3,0.0,fb495f9f9015a772,https://books.toscrape.com/catalogue/kindle-pa...,30,False,Medium,Low

In [ ]:
#Part D: Combining or Comparing Datasets - 15 Marks
#Students must use both datasets together in a meaningful way. There are two acceptable approaches.

#Option 1: Merge the Datasets
#If both datasets have a common column, students should merge them.
#Column used for merging

#The datasets were merged using the title column because both datasets contained book titles.

#Merge type used

#An inner join was used to keep only records that existed in both datasets.

#Rows before and after merging
print("Rows in scraped dataset:", len(df_scraped))
print("Rows in external dataset:", len(df_external))
print("Rows after merging:", len(merged_df))
#Missing values after mergin
print("Missing values after mergin:")
merged_df.isna().sum()

Rows in scraped dataset: 1000
Rows in external dataset: 998
Rows after merging: 1
Missing values after mergin:

title                0
price_gbp            0
rating_numeric       0
availability_x       0
product_link         0
page                 0
title_length_x       0
is_expensive_x       0
price_level_x        0
rating_level         0
availability_y       0
category             0
description          0
num_reviews          0
price                0
price_excl_tax       0
price_incl_tax       0
product_type         0
stars                0
tax                  0
upc                  0
url                  0
title_length_y       0
is_expensive_y       0
price_level_y        0
review_popularity    0
dtype: int64

In [ ]:
#Option 2: Compare the Datasets
#If the datasets cannot be merged directly, students should compare them using similar features.



#Comparison Result 1: Average Book Price
print("Average price in scraped dataset:")
print(df_scraped["price_gbp"].mean())

print("\nAverage price in external dataset:")
print(df_external["price"].mean())

Average price in scraped dataset:
35.07035

Average price in external dataset:
35.05292585170341

In [ ]:
#Comparison Result 2: Rating Distribution

print("Scraped dataset ratings:")
print(df_scraped["rating_numeric"].value_counts().sort_index())

print("\nExternal dataset ratings:")
print(df_external["stars"].value_counts().sort_index())

Scraped dataset ratings:
rating_numeric
1    226
2    196
3    203
4    179
5    196
Name: count, dtype: int64

External dataset ratings:
stars
1    225
2    196
3    202
4    179
5    196
Name: count, dtype: int64

In [ ]:
#Comparison Result 3: Availability Comparison
print("Scraped dataset availability:")
print(df_scraped["availability"].value_counts())

print("\nExternal dataset availability:")
print(df_external["availability"].value_counts())

Scraped dataset availability:
availability
In stock    1000
Name: count, dtype: int64

External dataset availability:
availability
3     196
14    136
1      97
15     86
16     84
5      65
7      53
8      47
4      47
6      35
12     34
11     28
9      25
19     23
2      14
18     11
17      5
13      5
20      4
10      2
22      1
Name: count, dtype: int64

In [ ]:
#Comparison Result 4 (Optional Extra): Expensive Books
scraped_expensive = (df_scraped["price_gbp"] > df_scraped["price_gbp"].mean()).sum()
external_expensive = (df_external["price"] > df_external["price"].mean()).sum()

print("Expensive books in scraped dataset:", scraped_expensive)
print("Expensive books in external dataset:", external_expensive)

Expensive books in scraped dataset: 513
Expensive books in external dataset: 513

In [ ]:
#Comparison Result 5 (Optional Extra): Price Statistics
print("Scraped dataset:")
print(df_scraped["price_gbp"].agg(["mean", "min", "max"]))

print("\nExternal dataset:")
print(df_external["price"].agg(["mean", "min", "max"]))

Scraped dataset:
mean    35.07035
min     10.00000
max     59.99000
Name: price_gbp, dtype: float64

External dataset:
mean    35.052926
min     10.000000
max     59.990000
Name: price, dtype: float64

In [ ]:
#Part E: NumPy for AI Computing - 15 Marks
#Students must use NumPy to perform numerical operations on the cleaned dataset.

In [ ]:
#1. Convert price column to NumPy array
#Scraped dataset
# Convert selected columns to NumPy array
numeric_data = df_scraped[
    ["price_gbp", "rating_numeric", "title_length"]
].to_numpy()

# Check shape
print(numeric_data.shape)

# View first 5 rows
print(numeric_data[:5])

(1000, 3)
[[51.77  3.   20.  ]
 [53.74  1.   18.  ]
 [50.1   1.   10.  ]
 [47.82  4.   13.  ]
 [54.23  5.   37.  ]]

In [ ]:
#Explanation for your report
#Shape of the array
#The shape of the NumPy array is:
#(1000, 3)

#Number of rows and columns
#Rows (1000): represent individual books collected from the website.
#Columns (3): represent the numerical features selected for AI processing.

#Meaning of each numerical column
#Column	                   Meaning
#price_gbp	               Price of the book in British Pounds (£)
#rating_numeric	           Numerical rating of the book from 1 to 5 stars
#title_length	           Number of characters in the book title

In [ ]:
#1-1. Convert price column to NumPy array
#External dataset
numeric_data_external = df_external[
    ["price", "stars", "num_reviews"]
].to_numpy()

print(numeric_data_external.shape)
print(numeric_data_external[:5])

(998, 3)
[[13.99  2.    0.  ]
 [50.1   1.    0.  ]
 [22.65  1.    0.  ]
 [54.23  5.    0.  ]
 [53.74  1.    0.  ]]

In [ ]:
#Explanation for your report for External dataset
#Shape of the array
#The shape of the NumPy array is:
#(998, 3)

#Number of rows and columns
# 998 rows represent the individual book records in the external dataset.
# 3 columns represent the selected numerical features that were converted into a NumPy array for AI-related numerical computations.

#Meaning of each numerical column
#Column	                   Meaning
#price	                   The selling price of the book.
#stars	                   The book's rating represented numerically using stars (typically from 1 to 5).
#num_reviews	           The total number of customer reviews associated with the book.

In [ ]:
#2 Basic NumPy Statistics  For your df_scraped dataset :
df_scraped["title_length"] = df_scraped["title"].str.len()

numeric_data = df_scraped[
    ["price_gbp", "rating_numeric", "title_length"]
].to_numpy()

import numpy as np

print("Mean:")
print(np.mean(numeric_data, axis=0))

print("\nMedian:")
print(np.median(numeric_data, axis=0))

print("\nStandard Deviation:")
print(np.std(numeric_data, axis=0))

print("\nMinimum:")
print(np.min(numeric_data, axis=0))

print("\nMaximum:")
print(np.max(numeric_data, axis=0))

Mean:
[35.07035  2.923   39.119  ]

Median:
[35.98  3.   35.  ]

Standard Deviation:
[14.43946452  1.43424928 25.76999882]

Minimum:
[10.  1.  2.]

Maximum:
[ 59.99   5.   205.  ]

In [ ]:
#2-1. Basic NumPy Statistics  For your external dataset:
numeric_data = df_external[
    ["price", "stars", "num_reviews"]
].to_numpy()
import numpy as np

print("Mean:")
print(np.mean(numeric_data, axis=0))

print("\nMedian:")
print(np.median(numeric_data, axis=0))

print("\nStandard Deviation:")
print(np.std(numeric_data, axis=0))

print("\nMinimum:")
print(np.min(numeric_data, axis=0))

print("\nMaximum:")
print(np.max(numeric_data, axis=0))

Mean:
[35.05292585  2.9248497   0.        ]

Median:
[35.98  3.    0.  ]

Standard Deviation:
[14.43907136  1.4343914   0.        ]

Minimum:
[10.  1.  0.]

Maximum:
[59.99  5.    0.  ]

In [ ]:
#3. Vectorized Computation
#Students must perform at least 2 vectorized operations.
# Vectorized Operation 1: Convert price from GBP to USD
df_scraped["price_usd"] = df_scraped["price_gbp"] * 1.27

# Vectorized Operation 2: Standardize (z-score normalize) the price
df_scraped["normalized_price"] = (
    df_scraped["price_gbp"] - np.mean(df_scraped["price_gbp"])
) / np.std(df_scraped["price_gbp"])
# Display results
df_scraped[["price_gbp", "price_usd", "normalized_price"]].head()

   price_gbp  price_usd  normalized_price
0      51.77    65.7479          1.156528
1      53.74    68.2498          1.292960
2      50.10    63.6270          1.040873
3      47.82    60.7314          0.882972
4      54.23    68.8721          1.326895

In [ ]:
#3.1
# Vectorized Operation 1: Convert price to USD

df_external["price_usd"] = df_external["price"] * 1.27

# Vectorized Operation 2: Standardize price
# (Z-score normalization)

df_external["normalized_price"] = (
    df_external["price"] - np.mean(df_external["price"])
) / np.std(df_external["price"])

# Display results
df_external[["price", "price_usd", "normalized_price"]].head()

   price  price_usd  normalized_price
0  13.99    17.7673         -1.458745
1  50.10    63.6270          1.042108
2  22.65    28.7655         -0.858984
3  54.23    68.8721          1.328138
4  53.74    68.2498          1.294202

In [ ]:
#4. Normalization or Standardization
#Students must normalize or standardize at least 2 numerical columns.
# Price normalization
df_scraped["price_normalized"] = (
    df_scraped["price_gbp"] - df_scraped["price_gbp"].min()
) / (
    df_scraped["price_gbp"].max() - df_scraped["price_gbp"].min()
)

# Rating normalization
df_scraped["rating_normalized"] = (
    df_scraped["rating_numeric"] - df_scraped["rating_numeric"].min()
) / (
    df_scraped["rating_numeric"].max() - df_scraped["rating_numeric"].min()
)

# Price standardization
df_scraped["price_standardized"] = (
    df_scraped["price_gbp"] - df_scraped["price_gbp"].mean()
) / df_scraped["price_gbp"].std()

# Rating standardization
df_scraped["rating_standardized"] = (
    df_scraped["rating_numeric"] - df_scraped["rating_numeric"].mean()
) / df_scraped["rating_numeric"].std()

In [ ]:
#4.1 Normalization or Standardization for external dataset
#Students must normalize or standardize at least 2 numerical columns.
# Price normalization
df_external["price_normalized"] = (
    df_external["price"] - df_external["price"].min()
) / (
    df_external["price"].max() - df_external["price"].min()
)

# Number of reviews normalization
df_external["reviews_normalized"] = (
    df_external["num_reviews"] - df_external["num_reviews"].min()
) / (
    df_external["num_reviews"].max() - df_external["num_reviews"].min()
)
# Price standardization
df_external["price_standardized"] = (
    df_external["price"] - df_external["price"].mean()
) / df_external["price"].std()

# Review standardization
df_external["reviews_standardized"] = (
    df_external["num_reviews"] - df_external["num_reviews"].mean()
) / df_external["num_reviews"].std()

In [ ]:
#Why is normalization useful for AI data preparation?
"""You can use the following paragraph directly in your report:

Normalization and standardization are important preprocessing steps
in Artificial Intelligence and Machine Learning. Numerical
features often have different scales; for example, book prices
may range from 0 to 60, while ratings range from 1 to 5. If data is
not scaled, features with larger values may dominate the learning process
and negatively affect model performance. Normalization transforms values to
a common range, typically between 0 and 1, while standardization transforms
data to have a mean of 0 and a standard deviation of 1. These techniques improve
model convergence, training stability, and prediction accuracy."""

'You can use the following paragraph directly in your report:\n\nNormalization and standardization are important preprocessing steps \nin Artificial Intelligence and Machine Learning. Numerical\nfeatures often have different scales; for example, book prices\nmay range from 0 to 60, while ratings range from 1 to 5. If data is\nnot scaled, features with larger values may dominate the learning process\nand negatively affect model performance. Normalization transforms values to\na common range, typically between 0 and 1, while standardization transforms\ndata to have a mean of 0 and a standard deviation of 1. These techniques improve\nmodel convergence, training stability, and prediction accuracy.'

In [ ]:
#5. Feature Matrix Representation
X_scraped = df_scraped[
    ["price_gbp", "rating_numeric", "title_length"]
].to_numpy()

print(X_scraped.shape)
print(X_scraped[:5])

(1000, 3)
[[51.77  3.   20.  ]
 [53.74  1.   18.  ]
 [50.1   1.   10.  ]
 [47.82  4.   13.  ]
 [54.23  5.   37.  ]]

In [ ]:
#5. Feature Matrix Representation for external dataset
X_external = df_external[
    ["price", "stars", "num_reviews"]
].to_numpy()

print(X_external.shape)
print(X_external[:5])

(998, 3)
[[13.99  2.    0.  ]
 [50.1   1.    0.  ]
 [22.65  1.    0.  ]
 [54.23  5.    0.  ]
 [53.74  1.    0.  ]]

In [ ]:
#Part F: Final AI-Ready Dataset Preparation - 5 Marks
# Remove duplicates
df_scraped = df_scraped.drop_duplicates()

# Remove rows with missing values
df_scraped = df_scraped.dropna()

# Save final AI-ready dataset
df_scraped.to_csv(
    "ai_ready_scraped_dataset.csv",
    index=False,
    encoding="utf-8"
)

print("AI-ready scraped dataset saved successfully.")
print("Shape:", df_scraped.shape)

AI-ready scraped dataset saved successfully.
Shape: (1000, 16)

In [ ]:
#Part F: Final AI-Ready Dataset Preparation - 5 Marks

# Remove duplicates
df_external = df_external.drop_duplicates()

# Fill missing values according to column type
for col in df_external.columns:
    if df_external[col].dtype == "object":
        # Text columns
        df_external[col] = df_external[col].fillna("Unknown")
    elif str(df_external[col].dtype) == "category":
        # Categorical columns
        df_external[col] = df_external[col].cat.add_categories(["Unknown"])
        df_external[col] = df_external[col].fillna("Unknown")
    else:
        # Numeric columns
        df_external[col] = df_external[col].fillna(df_external[col].median())

# Save AI-ready dataset
df_external.to_csv(
    "ai_ready_external_dataset.csv",
    index=False,
    encoding="utf-8"
)

print("Final shape:", df_external.shape)

Final shape: (998, 23)

In [ ]:

print(df_external.dtypes)

availability               int64
category                  object
description               object
num_reviews                int64
price                    float64
price_excl_tax           float64
price_incl_tax           float64
product_type              object
stars                      int64
tax                      float64
title                     object
upc                       object
url                       object
title_length               int64
is_expensive                bool
price_level             category
review_popularity       category
price_usd                float64
normalized_price         float64
price_normalized         float64
reviews_normalized       float64
price_standardized       float64
reviews_standardized     float64
dtype: object

In [ ]:
# Use the cleaned dataframe
df_scraped_clean = df_scraped.copy()

print(df_scraped_clean.shape)

df_scraped_clean = pd.read_csv('scraped_with_features.csv') if 'scraped_with_features.csv' in globals() else df_scraped_clean

(1000, 16)

In [ ]:
#Option 1: Merge the Datasets

# ============================================
# PART D: COMBINING OR COMPARING DATASETS
# ============================================

print("\n" + "="*60)
print("PART D: DATASET COMBINING OR COMPARISON")
print("="*60)

# First, ensure we have cleaned datasets with engineered features
# Use the cleaned scraped dataset with features
df_scraped_clean = pd.read_csv('scraped_with_features.csv') if 'scraped_with_features.csv' in globals() else df_scraped_clean

# Check if external dataset exists
if 'df_external' not in locals():
    print("Loading external dataset...")
    df_external = pd.read_csv('external_raw_dataset.csv')

print(f"Scraped dataset shape: {df_scraped_clean.shape}")
print(f"External dataset shape: {df_external.shape}")

print("\n" + "="*60)
print("OPTION 1: MERGING DATASETS")
print("="*60)

============================================================
PART D: DATASET COMBINING OR COMPARISON
============================================================
Scraped dataset shape: (1000, 16)
External dataset shape: (998, 23)

============================================================
OPTION 1: MERGING DATASETS
============================================================

In [ ]:
merged_df = pd.merge(
    df_scraped,
    df_external,
    on="title",
    how="inner"
)

print("Rows in scraped dataset:", len(df_scraped))
print("Rows in external dataset:", len(df_external))
print("Rows after merge:", len(merged_df))

print(merged_df.isna().sum())

Rows in scraped dataset: 1000
Rows in external dataset: 998
Rows after merge: 1
title                   0
price_gbp               0
rating_numeric          0
availability_x          0
product_link            0
page                    0
title_length_x          0
is_expensive_x          0
price_level_x           0
rating_level            0
price_usd_x             0
normalized_price_x      0
price_normalized_x      0
rating_normalized       0
price_standardized_x    0
rating_standardized     0
availability_y          0
category                0
description             0
num_reviews             0
price                   0
price_excl_tax          0
price_incl_tax          0
product_type            0
stars                   0
tax                     0
upc                     0
url                     0
title_length_y          0
is_expensive_y          0
price_level_y           0
review_popularity       0
price_usd_y             0
normalized_price_y      0
price_normalized_y      0
reviews_normalized      1
price_standardized_y    0
reviews_standardized    1
dtype: int64

In [ ]:
#Option 1: Merge the Datasets

• Explain which column was used for merging.
    The datasets were merged using the title column because both datasets contain the book title, which serves as the common identifier between the two datasets.
• Explain which merge type was used.
    how="inner"
    An Inner Join was used. This merge type keeps only the records where the book title exists in both the scraped dataset and the external dataset.
• Report how many rows existed before and after merging.
    Rows in scraped dataset: 1000
    Rows in external dataset: 1000
    Rows after merge: 1002
• Explain whether missing values were created after merging.
        title               0
price_gbp_x         0
rating_numeric_x    0
availability_x      0
product_link_x      0
page_x              0
title_length        0
is_expensive        0
price_level         0
rating_level        0
price_gbp_y         0
rating_numeric_y    0
availability_y      0
product_link_y      0
page_y              0
dtype: int64

SyntaxError: invalid character '•' (U+2022) (595801340.py, line 3)

In [ ]:
#Option 2: Compare the Datasets

print(df_external.columns)
df_external.info()

Index(['availability', 'category', 'description', 'num_reviews', 'price',
       'price_excl_tax', 'price_incl_tax', 'product_type', 'stars', 'tax',
       'title', 'upc', 'url', 'title_length', 'is_expensive', 'price_level',
       'review_popularity', 'price_usd', 'normalized_price',
       'price_normalized', 'reviews_normalized', 'price_standardized',
       'reviews_standardized'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 998 entries, 0 to 997
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   availability          998 non-null    int64
 1   category              998 non-null    object
 2   description           998 non-null    object
 3   num_reviews           998 non-null    int64
 4   price                 998 non-null    float64
 5   price_excl_tax        998 non-null    float64
 6   price_incl_tax        998 non-null    float64
 7   product_type          998 non-null    object
 8   stars                 998 non-null    int64
 9   tax                   998 non-null    float64
 10  title                 998 non-null    object
 11  upc                   998 non-null    object
 12  url                   998 non-null    object
 13  title_length          998 non-null    int64
 14  is_expensive          998 non-null    bool
 15  price_level           998 non-null    category
 16  review_popularity     998 non-null    category
 17  price_usd             998 non-null    float64
 18  normalized_price      998 non-null    float64
 19  price_normalized      998 non-null    float64
 20  reviews_normalized    0 non-null      float64
 21  price_standardized    998 non-null    float64
 22  reviews_standardized  0 non-null      float64
dtypes: bool(1), category(2), float64(10), int64(4), object(6)
memory usage: 159.4+ KB

In [ ]:
print("Average Price (Scraped):")
print(df_scraped["price_gbp"].mean())

print("Average Price (External):")
print(df_external["price"].mean())

Average Price (Scraped):
35.07035
Average Price (External):
35.05292585170341

In [ ]:
print("Scraped Dataset Ratings")
print(df_scraped["rating_numeric"].value_counts().sort_index())

print("\nExternal Dataset Ratings")
print(df_external["stars"].value_counts().sort_index())

Scraped Dataset Ratings
rating_numeric
1    226
2    196
3    203
4    179
5    196
Name: count, dtype: int64

External Dataset Ratings
stars
1    225
2    196
3    202
4    179
5    196
Name: count, dtype: int64

In [ ]:
clean_scraped_dataset = df_scraped.copy()

clean_scraped_dataset.to_csv(
    "clean_scraped_dataset.csv",
    index=False,
    encoding="utf-8"
)

In [ ]:
clean_external_dataset = df_external.copy()

clean_external_dataset.to_csv(
    "clean_external_dataset.csv",
    index=False,
    encoding="utf-8"
)

In [ ]:

#final ai_ready_dataset.csv
# Prepare scraped dataset
scraped_ai = df_scraped.copy()

scraped_ai["dataset_source"] = "web_scraped"

# Rename columns to match external dataset
scraped_ai = scraped_ai.rename(columns={
    "price_gbp": "price",
    "rating_numeric": "stars",
    "product_link": "url"
})

# Add missing columns
scraped_ai["category"] = "Unknown"
scraped_ai["description"] = "Unknown"
scraped_ai["num_reviews"] = 0
scraped_ai["tax"] = 0
scraped_ai["upc"] = "Unknown"

In [ ]:
external_ai = df_external.copy()

external_ai["dataset_source"] = "external"

In [ ]:
common_columns = [
    "title",
    "price",
    "stars",
    "availability",
    "url",
    "category",
    "description",
    "num_reviews",
    "tax",
    "upc",
    "dataset_source"
]

scraped_ai = scraped_ai[common_columns]
external_ai = external_ai[common_columns]

In [ ]:
ai_ready_dataset = pd.concat(
    [scraped_ai, external_ai],
    ignore_index=True
)

print(ai_ready_dataset.shape)

(1998, 11)

In [ ]:
ai_ready_dataset = ai_ready_dataset.fillna("Unknown")
ai_ready_dataset = ai_ready_dataset.drop_duplicates()

In [ ]:
ai_ready_dataset.to_csv(
    "ai_ready_dataset.csv",
    index=False,
    encoding="utf-8"
)

print("AI-ready dataset saved successfully.")
print("Final shape:", ai_ready_dataset.shape)

AI-ready dataset saved successfully.
Final shape: (1998, 11)

In [ ]:


#12. Expected Final Output Example
ai_ready_dataset = df_scraped[
    [
        "title",
        "price_gbp",
        "rating_numeric",
        "title_length",
        "price_level",
        "is_expensive"
    ]
].copy()

# Rename price_gbp to price
ai_ready_dataset.rename(
    columns={"price_gbp": "price"},
    inplace=True
)

# Save final dataset
ai_ready_dataset.to_csv(
    "ai_ready_dataset.csv",
    index=False,
    encoding="utf-8"
)

print(ai_ready_dataset.head())
print(ai_ready_dataset.shape)

                                   title  price  rating_numeric  title_length  \
0                   A Light in the Attic  51.77               3            20
1                     Tipping the Velvet  53.74               1            18
2                             Soumission  50.10               1            10
3                          Sharp Objects  47.82               4            13
4  Sapiens: A Brief History of Humankind  54.23               5            37

  price_level  is_expensive
0        High          True
1        High          True
2        High          True
3        High          True
4        High          True
(1000, 6)